_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "internal"

      oidc_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: "openid"
          challenge: true
          config:
            subject_key: "preferred_username"
            roles_key: "roles"
            openid_connect_url: "https://sso-dev.odd.works/realms/poc/.well-known/openid-configuration"
            jwks_uri: "https://sso-dev.odd.works/realms/poc/protocol/openid-connect/certs"
            client_id: "opensearch"
            client_secret: "WVJopMegKL0Hk3jK2nfOmglpBxXTaQo"
        authentication_backend:
          type: noop